### ISSUE TITLE
Broken link to Tile Dev Guide

### ISSUE THREAD

**Issue by AmberAlston** [cloudfoundry/docs-bbr#14]
For this sentence, "For more information about how PCF tile authors can implement the BBR contract, see the PCF Tile Developer Guide.", the link out (https://docs.pivotal.io/tiledev/2-0/bbr-devguide.html) does not exist and renders a broken page

**Comment by animatedmax** [comment]
Hi @AmberAlston I don't know what happened to this story, but the BBR documentation no longer appears to link to the Tile Developer Guide.
