### ISSUE TITLE
Broken Links in Readme.md

### ISSUE THREAD

**Issue by MirahImage** [cloudfoundry/docs-bbr#25]
- Line 27: https://github.com/pivotal-cf/docs-book-pcfservices/blob/master/master_middleman/source/subnavs/bbr-subnav.erb
- Line 31: https://github.com/pivotal-cf/docs-book-pcfservices/blob/master/config/template_variables.yml
- Line 69: https://github.com/pivotal-cf/docs-book-pcfservices/blob/master/master_middleman/source/subnavs/bbr-subnav.erb
- Line 89: https://github.com/pivotal-cf/docs-book-pcfservices/blob/master/config/template_variables.yml
- Line 104: https://github.com/pivotal-cf/docs-book-pivotalcf/blob/master/master_middleman/source/subnavs/pcf-subnav.erb

**Comment by mjgutermuth** [comment]
Hi @MirahImage! I'm taking a look at this now, but the line numbers aren't matching up since the files have changed since you created the issue. I checked the links in the files you listed and they seem valid. Is it possible these broken links have already been resolved?

**Comment by MirahImage** [comment]
It's quite possible that the broken links were fixed by another commit since we opened the issue. I'm going to go ahead and close this issue. Thanks for looking into it.
